- hosts: server
  become: true
  roles:
    - system
    - geerlingguy.docker
  tasks:
    - name: Set service_cfg for traefik
      set_fact:
        service_cfg: "{{ traefik }}"
    - name: Deploy Traefik
      include_role:
        name: traefik
    - name: Set service_cfg for watchtower
      set_fact:
        service_cfg: "{{ watchtower }}"
    - name: Deploy Watchtower
      include_role:
        name: watchtower
    - name: Set service_cfg for autoheal
      set_fact:
        service_cfg: "{{ autoheal }}"
    - name: Deploy Autoheal
      include_role:
        name: autoheal
    - name: Set service_cfg for portainer
      set_fact:
        service_cfg: "{{ portainer }}"
    - name: Deploy Portainer
      include_role:
        name: portainer